package main

import (
	"fmt"
)

func main() {

	var twos, threes int
	for _, line := range input {
		var counts [26]int8
		for _, c := range line {
			counts[c-'a']++
		}
		for _, count := range counts {
			if count == 2 {
				twos++
				break
			}
		}
		for _, count := range counts {
			if count == 3 {
				threes++
				break
			}
		}
	}
	fmt.Println(twos * threes)

	// Differ by exactly one character.
	// Brute force
ALL:
	for _, a := range input {
	NEXT:
		for _, b := range input {
			if a == b {
				continue
			}

			pos := -1
			for i := range a {
				if a[i] != b[i] {
					if pos != -1 {
						continue NEXT
					}
					pos = i
				}
			}
			if pos != -1 {
				fmt.Println(a[:pos] + a[pos+1:])
				break ALL
			}
		}
	}
}

var input = []string{
	"kqzxdenujwcsthbzgvyioflcsp",
	"vqwxdenujwcsthbmggyioflarp",
	"kqzxienujwcsthbmglyioclarp",
	"kuzxdetujwcsthbmgvyioflcrp",
	"kqnxdenujwcsthbmgvlooflarp",
	"kqzxdknpjwcsthwmgvyioflarp",
	"kgzxdenujwcsthbfgvyicflarp",
	"kqzxdenujrnsthbmgjyioflarp",
	"lqzxdeeujwcsthbmrvyioflarp",
	"iqfxdenujwcsthbmgvyiofyarp",
	"kvzxbenujwcstabmgvyioflarp",
	"kmzxdenujwcsthbmglyioolarp",
	"kqzxdenujhcsthbmgbyioflanp",
	"nqzxdenujwcsehbmgvsioflarp",
	"kqzlgenujwcsthbmgvyiofjarp",
	"kqzxdyfujwcsihbmgvyioflarp",
	"kqzxdsnujwcqthbmgvyiorlarp",
	"kqzxdenuywcsthbmgvyinflmrp",
	"knzxderujwcsthbmgvyioflaop",
	"kqxxdenujwczthbmgvyioflajp",
	"kqzxdevujwcsthbmgvyqoxlarp",
	"kqzxdenujwclmhbmgvyioslarp",
	"kqzldenujwcsthbmgvnisflarp",
	"kjtxdenujwcsthbmgvyfoflarp",
	"kqzxwenujwcstxbmgvyihflarp",
	"kqzxdenuhecsthbmgvyeoflarp",
	"kqzxdenhjwesthbmgvyioklarp",
	"kqkxdenujwcsthbcgvyiofgarp",
	"kqyxmenujwcsthbmgvyioflara",
	"kqzxdqnrjwcwthbmgvyioflarp",
	"kqzxdenufwcgyhbmgvyioflarp",
	"lqzxdenujwcsthbmtvyiofearp",
	"kqzxdenujwcsthbvgvthoflarp",
	"kqzxeenujwcsahbmgvyioflamp",
	"pqzxdenujwcsshbmjvyioflarp",
	"kqzxdesujwcstdbmgvyioflatp",
	"kqzxpenujwcsthimgvyioflhrp",
	"kqzxdmkujwcsthbmgvpioflarp",
	"kszxdenujwcsthbybvyioflarp",
	"kqzxdvnujwcsthbmgvyqoslarp",
	"kkzxdetujwcsthbmgvyiofltrp",
	"kqzxdenujwcsthomgvyiozlaro",
	"cqzfdenubwcsthbmgvyioflarp",
	"kqzxdenyjwcsthbmhvyiofldrp",
	"kqzxdenujwcsthbmghfiofxarp",
	"kmqxdebujwcsthbmgvyioflarp",
	"kqzxdenufwcsthbmvvypoflarp",
	"kqnxdenujwcsthbmgvtzoflarp",
	"bqzxdenujwcithbmgvyiohlarp",
	"kqzxdenurwrsthbmgvyioelarp",
	"kqzxdenujwcsthbmgpyiodlarl",
	"kqzxdengjwcxthbmgvjioflarp",
	"kizxdenujwcsnhqmgvyioflarp",
	"jqzxdenajwcsthbmnvyioflarp",
	"kqzcdenujwcsphbigvyioflarp",
	"kezxdenujwcsthbfgvyioflaqp",
	"kqzxdenujwcstybmgvyivfyarp",
	"kqzxdenujwcsthbmgvbiofsnrp",
	"kqzxdenujwcsthbmgvyhxfnarp",
	"kvzxdenqjfcsthbmgvyioflarp",
	"kqzxywnljwcsthbmgvyioflarp",
	"kqzxdenujwcsbhbzgvyioxlarp",
	"kqkxdenufwcsthbmgvyiofxarp",
	"dqzxddnujwcsthsmgvyioflarp",
	"yqrxdenujwcsthbagvyioflarp",
	"kqzxdenujwcsajbmgvyiovlarp",
	"kqztdunujwcsthbmgvyioilarp",
	"kqzxdequjwcsthbmgvyyoflarm",
	"kqzxdlnujwksthbmgvkioflarp",
	"tqvxdenujwcsthbmgveioflarp",
	"kqzndezupwcsthbmgvyioflarp",
	"kqzctsnujwcsthbmgvyioflarp",
	"kqzxdenujwmstkbmgvyioflgrp",
	"kqzxdenujwzsthdmgvyiofdarp",
	"kqzxdynujwcsthcmgvyioflasp",
	"kqzxdesujwcstybmgcyioflarp",
	"kqzxdenujwcsthbvgvyiyglarp",
	"kqzxpenujwcsthbogvyioflard",
	"khzxdenujwcsthbmgvyikflaep",
	"kqzxdedujwchthbmgvyeoflarp",
	"kxzxsepujwcsthbmgvyioflarp",
	"xqzxdenujwcsthbpgvyioelarp",
	"jfzxdenujwcsthbmgvyiollarp",
	"kqzxcenujwcethbmgvwioflarp",
	"kqzxdenujwcithbmgvysoflarg",
	"kqlxdenujwnsthbmgvyiotlarp",
	"wqzydenujwcsthbmgvyioftarp",
	"kqzxienuwwcsthbmgayioflarp",
	"kqzxdetujwcsthbmgvyhoflawp",
	"kqzxdqnujwrsthbmgvyxoflarp",
	"kqzxdenujwcvthbmgjiioflarp",
	"kqzxdenujwcjthbxgvaioflarp",
	"kqzxpenujwcsthymgvyioklarp",
	"kqzxdenujwcsthbmswygoflarp",
	"kqzxdenujwcsthbmgvyiaxiarp",
	"kqzxdenudkcsthbmgvyzoflarp",
	"kqzxdvndjwcsthbmgvyioflaxp",
	"kqzxdenujwcsthbmdvymoflvrp",
	"kqzxvenujwcsihbmgvyiofllrp",
	"kqzxdqnujwcsthbmgtyioflprp",
	"kqzxdenuuwcathbmgvsioflarp",
	"kqzrdenujwesthbjgvyioflarp",
	"kqzxdexujwcstzbmgvyyoflarp",
	"kqzxpenujwjstabmgvyioflarp",
	"kozxdenejwcsthbmgvpioflarp",
	"kbzxdenvjwcsthbmgvyiofsarp",
	"kolxdenujwcjthbmgvyioflarp",
	"kqzxdenujwcsthbmgvyiffsakp",
	"kqzxdelujwcsthbmlvyioflxrp",
	"kqzxdenugwcsthrmgvyioflprp",
	"kqzxdelujwcsthqmgvyiozlarp",
	"kqzxienujwosthbmgvykoflarp",
	"kqzxdeuujwicthbmgvyioflarp",
	"kqzxdenbjwcsthbmcvyaoflarp",
	"krzxdqnujwcsthbmgvyioflerp",
	"wqzxzenujwcsthbmgvyioclarp",
	"kqzxyenujwcsthbmgejioflarp",
	"kqzxdenujwcstsbmgvtidflarp",
	"kqnxdenejwcsthbmgvyioflara",
	"kqzsdmnujwcsthbmgvyioflaep",
	"kqzxdedujwnsthymgvyioflarp",
	"kqzxdenujwusthbmgnyioflarx",
	"kqzxlenujwcsthbmgayvoflarp",
	"kqzxdenujwcsthbmgvyiofngrh",
	"zqzxdenujwcsthbmgvyiofvxrp",
	"kqzydenujwmsthbmgvyiuflarp",
	"kqzxdenujkrsthbmdvyioflarp",
	"kqzxdlnujocsthbmgvyiofaarp",
	"kqzxdenujwcstybmgvyiofrwrd",
	"kqzxdenupwksthbmgvyiofbarp",
	"khzxdentjwcsthbmbvyioflarp",
	"kqzxdenujwcuphbmgvyihflarp",
	"kqzxdenhjwcgthbmgvyioflrrp",
	"kqzxdenujwcsthbmgvyiofakhp",
	"kqzxdenujwcstfkmgvyioflamp",
	"kqzxdenujqcsthbmgvkiorlarp",
	"kqzxdenujwcstvbmgvyioilasp",
	"kqzxdxnujwcsthbpgayioflarp",
	"kqzxdenupwysthbmgvyiofljrp",
	"kqzxdenujwcdthbmgvymoflarv",
	"kqnxdenujwcstvbmgvyixflarp",
	"kqjxdenujwcsthbmgvyikflurp",
	"kqsxdenulwcsthxmgvyioflarp",
	"bqzxbenujwcsahbmgvyioflarp",
	"vqzxdenujwcsthbmgvjzoflarp",
	"kqzhfenujwcsthimgvyioflarp",
	"eqzxdenujwcshhbmgnyioflarp",
	"kqzxdenujucstubmgvyicflarp",
	"kuzxdenuewcsthbmgvyiofuarp",
	"kqzxdenulwcsthbmgpyigflarp",
	"kqzxdebujwcsthbmgoyioflaro",
	"kqzxdenujwcuthbmgucioflarp",
	"kqzxdenujwcschpmgvyioflhrp",
	"kqzxfenujwcsthbmjvrioflarp",
	"kqzxdenujqcsthbmgvyndflarp",
	"kqzxdgnbjwcsthbmgvywoflarp",
	"kqzxdenujwcsthrmgtbioflarp",
	"yqzxdenyjwcsthbmgvyioflarg",
	"kqzxdenuxwxsthbmsvyioflarp",
	"kqzxdenujwcsthbugqyvoflarp",
	"qqzxdenujwcsahbmgoyioflarp",
	"kqsxdenudwcsthbmguyioflarp",
	"kqzxdenujwcstublgvyioflamp",
	"kqzxdemujwtstqbmgvyioflarp",
	"kqzxqvnajwcsthbmgvyioflarp",
	"kqzxoennjwcstbbmgvyioflarp",
	"kqzxfenujwcsthbmlvyioflwrp",
	"kqzjdunujwcsthhmgvyioflarp",
	"kqzxdenujwcqthbmgvyirfxarp",
	"kqzxdengjwcsthbmgvyiowlgrp",
	"kqgxdenujwcswhbmglyioflarp",
	"mqzxdekuuwcsthbmgvyioflarp",
	"kqzxdenujwdsthbmgbyiovlarp",
	"krzxdenlhwcsthbmgvyioflarp",
	"kqzxdenmjwcstqbmgvyioflanp",
	"kqzxdenujwcmthbmgvtioflyrp",
	"kqzxdenujwcsthbmgvaijflprp",
	"kqzxdenuywysqhbmgvyioflarp",
	"kqzxdenujwfsthbmgvyhoflark",
	"nqzcdefujwcsthbmgvyioflarp",
	"kqzxdenujrcsthgmgyyioflarp",
	"kqzxdqnujwzsthbmgvyioftarp",
	"kqzxdenujwcsthimgvyioolapp",
	"kqzxdenupwcsthbmggyioflyrp",
	"kqzxdjnujwcsthbvgvyioflarf",
	"kqzxdtnujwasthbmgvyiofuarp",
	"kqzxbensjzcsthbmgvyioflarp",
	"kqzxdenujwcsphbmwiyioflarp",
	"kqzgdenuowcsthbmgvyioflarh",
	"kmzxdenujwasthbmgvtioflarp",
	"kqzxdenujwcstybmgvyiofrard",
	"vqzxdenejwcsthbmglyioflarp",
	"kqhxdenujwcsmhbmgvyioflprp",
	"kqzxdnnujwcsthzsgvyioflarp",
	"kczxdenujwcsthbmgvyeoflaop",
	"kqzxdenujwcsxhbmgvaioflaap",
	"kqzxdenujwcsthbmgayiofnprp",
	"kqzxdvnujwcsthbmgvyipjlarp",
	"kqzxdenubwcskhbmgvyiofkarp",
	"kqzxdenujwcsthbgggyigflarp",
	"kqzxdenujncstabvgvyioflarp",
	"kqzxdenujwcstqimqvyioflarp",
	"kqzxeenujwcsdhbmgvyqoflarp",
	"kcpxdenujwcsthbmgvyioilarp",
	"kqwxuenujwcsthbmgvyiyflarp",
	"kqzxdwnujwcstgbmgvyioplarp",
	"kqzxdenuswcstvbmglyioflarp",
	"kqzxdenujwcsthabgvyiwflarp",
	"kqzxdpnujwcsthbmwvyiomlarp",
	"kqzxdenujwcdthbmgvcioffarp",
	"kqzxdenajwcsthbmtvyiofldrp",
	"kqzbnenujwcshhbmgvyioflarp",
	"kqzbdequiwcsthbmgvyioflarp",
	"kqzxdenuswcsohbmgzyioflarp",
	"kvzxdenujwcstdbmjvyioflarp",
	"kqzxoenujwcqthbmpvyioflarp",
	"kqzxhenujwcsthbmgoyiofoarp",
	"klzxdenujwczthbmgvyioflanp",
	"kqpxdenujwcsthbmgvyioflafz",
	"kqkxdenujwcstxbngvyioflarp",
	"kqzepenuxwcsthbmgvyioflarp",
	"bqzxdenujmcithbmgvyioflarp",
	"kdzxdjnujwcstnbmgvyioflarp",
	"kszxdenujwcsthbmgeyiofrarp",
	"kqzxdenijwcsthbmgvhiaflarp",
	"kqzadenujwcbtxbmgvyioflarp",
	"kqkxwenujwcsthbmgvyiowlarp",
	"pqzddenujwcsthbmgvyboflarp",
	"kqzxxenujwcsthbwgvyioflmrp",
	"kqzxdjnujwcsthbmgvyipilarp",
	"pqzxdenujwcsthbmgvyieflark",
	"sqzxdenujtcsthbmgiyioflarp",
	"kqzxdznujwcsthbmgvzioflajp",
	"kqzxdrnujqcsthbmgvyiofvarp",
	"gqzxdenujwcsthemgvlioflarp",
	"kqzxdenujjcsthbmgvuiofljrp",
	"kqzsdenujmcsthbmggyioflarp",
	"kqzxienujwcsthbmgvaioflaip",
	"kqzxdwnujwcstfkmgvyioflarp",
	"kqzqdenujwcithbmzvyioflarp",
	"kqzxdedpjwcsthbmgvyiofbarp",
	"kqzxdeaujwcbtdbmgvyioflarp",
	"kqzewenyjwcsthbmgvyioflarp",
	"kqzxddnujwcsthbmgyyiofrarp",
	"kqzxdtnujwcsthbmgvyiodlard",
	"kqzxdefujwcsthbmgvyiffwarp",
	"xczxdenujwcsthbmgvyooflarp",
	"kuzxdenujucsthbmgvykoflarp",
	"kqzxtenujwcwthbmgvyioplarp",
	"kqzxdencllcsthbmgvyioflarp",
}
